# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170626_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this blog post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
